# Generated by Django 4.0.8 on 2024-03-22 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='UserRolePrivileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_privileges', to='exam.resources')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_resource', to='exam.customer')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_resource', to='exam.resources')),
            ],
        ),
    ]
