# Generated by Django 4.0.8 on 2024-03-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_resources_user_role_id_userroleprivileges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
