openapi: 3.0.3
info:
  title: LMS
  version: 0.0.0
paths:
  /api/schema:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /exam/courses/active/v1/:
    get:
      operationId: exam_courses_active_v1_retrieve
      description: |-
        view to display [active] courses list from course table that have original_course = null and version_number = 1
        trigger with GET request
        should be allowed for only [super admin].

        table : Course

        what will be displayed:
                    id
                    title
                    updated_at
                    version_number
      tags:
      - exam
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /exam/enrollments/assign/:
    post:
      operationId: exam_enrollments_assign_create
      description: |-
        this API is used to assign course to specified user(s) for all users in courseenrollment table who have active false
        in request body : list of ids of instance of course enrollment table

        Method: POST
        Parameters:
            - enrollment_ids (list of integers): IDs of course enrollment instances to assign, who have active status false for now

        It is triggered with POST request.
      tags:
      - exam
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /exam/enrollments/unassign/:
    post:
      operationId: exam_enrollments_unassign_create
      description: |-
        this API is used to unassign course to specified user(s) by turning the active false , and hide visibility of course to user(s).
        required inputs : list of ids of instance of course enrollment table

        Method: POST
        Parameters:
            - enrollment_ids (list of integers): IDs of course enrollment instances to unassign.

        It is triggered with POST request.
      tags:
      - exam
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
